### ISSUE TITLE
New release/ tag possible?

### ISSUE THREAD

**Issue by nerrehmit** [octodns/octodns-dnsimple#24]
I was wondering if it is possible to create an updated release or a new tag?

The only tag available is 0.0.1 from the https://github.com/octodns/octodns-dnsimple/blob/main/octodns_dnsimple/__init__.py#L5C1-L5C22 string in the __init__.py
from back in 2021.
The project has seen a bit of development and some dependencies were updated so I think a new release would be nice for all users who don't use the commit hashes for the versioning.

Thanks :)

**Comment by ross** [comment]
Hi @nerrehmit, looking over the changes since the v0.0.1 tag the only change that's not just formatting/linting or process/tooling related is the addition of a `user-agent` header, https://github.com/octodns/octodns-dnsimple/compare/v0.0.1...main#diff-9da4956bc34bd89944a48e498be6f04a612268d4b586fd88e11860565d5a5b2aR40. 

Everything else is a noop as far as the functioning provider is concerned. For the most part the provider does all the things it needs. 

The one thing that probably needs to be added is `def list_zones` so that the provider will support dynamic zone config, https://github.com/octodns/octodns/pull/1026.

**Comment by ross** [comment]
Release cut https://github.com/octodns/octodns-dnsimple/pull/27
